#Use this link to find a complete list of available achievements: https://pastebin.com/0T9NnaF2
#If true it will check plugin version in console
ConsoleCheckUpdate: true
#If true, players with portalblockerfree.updates will recieve an update message in chat (if plugin is not up to date)
CheckUpdate: true
Language: "en_US"
Prefix: "&7[PortalBlockerFree] "
#Every block type can be used with other block type (except for PermBlockTeleports)
PermBlockTeleports:
  #Block permanently lost end city portal use
  EGBlock: false
  #Block permanently end portal use
  EPBlock: false
  #Block permanently nether portal use
  NPBlock: false
#Block Teleportation use until achievement is completed
BlockThroughAchievement:
  #Block lost end city portal until achievement is not completed
  EGBlock: true
  #Block end portal until achievement is not completed
  EPBlock: true
  #Block nether portal until achievement is not completed
  NPBlock: true
#Block Portals creation
BlockPortalCreation:
  #Block Nether Portal Creation
  NPCreate: false
#Lost End City Portal
EndGateway:
  #For version older than 1.11.2 (1.11.2 included)
  Achievement: "THE_END"
  #Custom quest name that players will receive as a notice
  QuestName: "&aEnter The End City Gateway"
  #Numbers of block broken that a player need to use a nether portal
  BlockBreakOption: false
  BlockBreakNumberLimit: 25
  BlockBreakType: "SAND"
  #Numbers of block placed that a player need to use a nether portal
  BlockPlaceOption: false
  BlockPlaceNumberLimit: 25
  BlockPlaceType: "SAND"
  #If true, players will be notified (you can find it in lang files)
  ErrorMessage: true
  #If true, players will be notified (you can find it in lang files)
  PermBlockErrorMessage: true
#End Portal
EndPortal:
  #For version older than 1.11.2 (1.11.2 included)
  Achievement: "GET_BLAZE_ROD"
  #Custom quest name that players will receive as a notice
  QuestName: "&aMake An Ender Eye"
  #Numbers of block broken that a player need to use a nether portal
  BlockBreakOption: false
  BlockBreakNumberLimit: 25
  BlockBreakType: "SANDSTONE"
  #Numbers of block placed that a player need to use a nether portal
  BlockPlaceOption: false
  BlockPlaceNumberLimit: 25
  BlockPlaceType: "SANDSTONE"
  #If true, players will be notified (you can find it in lang files)
  ErrorMessage: true
  #If true, players will be notified (you can find it in lang files)
  PermBlockErrorMessage: true
#Nether Portal
NetherPortal:
  #For version older than 1.11.2 (1.11.2 included)
  Achievement: "GET_DIAMONDS"
  #Custom quest name that players will receive as a notice
  QuestName: "&aMine Obsidian"
  #Numbers of block broken that a player need to use a nether portal
  BlockBreakOption: false
  BlockBreakNumberLimit: 25
  BlockBreakType: "OBSIDIAN"
  #Numbers of block placed that a player need to use a nether portal
  BlockPlaceOption: false
  BlockPlaceNumberLimit: 25
  BlockPlaceType: "OBSIDIAN"
  #If true, players will be notified (you can find it in lang files)
  ErrorMessage: true
  #If true, players will be notified (you can find it in lang files)
  PermBlockErrorMessage: true
  #If true, it will automatically deactivate nether portal (if the player is not able to go through)
  Deactivate: true
  #Do not deactivate nether portals in this worlds
  DoNotIn:
    - 'hub'
    - 'lobby'
